### PR TITLE
Add rotation feature

### LINKED ISSUE #6: Support rotation
* xrandr-extend version: 0.2.0
* Python version: 3.7.4
* Operating System: Archlinux

### Description

Would it be possible to support screen rotation? Currently I have a 4k screen in horizontal and a 1080p screen in vertical on the right side.

### PR DESCRIPTION
**Pull request by akihironitta**
## Motivation
Closes #6.

## Description of the changes
This PR adds rotation feature as `xrandr` supports `--rotate normal,inverted,left,right` option.

### CODE REVIEW

**Comment by ashwinvis** [comment]
Hi @akihironitta let me know if you need any help with this.

**Comment by akihironitta** [comment]
@ashwinvis Thanks for pinging me! I'll try to work on this issue again early this week and reach you if I get stuck.

**Comment by akihironitta** [comment]
@ashwinviz I'm very sorry for my extreme inactivity. I have no resources at the moment to work on this, so please let me close this PR.

**Comment by ashwinvis** [comment]
No worries  @akihironitta. Thanks for trying.

**Pull request closed without merging**
